AWSTemplateFormatVersion: '2010-09-09'
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Habilitar acceso HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0521cb2d60cfbb1a6
      InstanceType: t3.micro
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          cat <<EOF > /var/www/html/index.html
          <!DOCTYPE html>
          <html>
          <head>
              <title>Examen Final</title>
              <style>body { font-family: Arial; text-align: center; margin-top: 50px; }</style>
          </head>
          <body>
              <h1>Daniel Alexis Sanguino Rodríguez</h1>
              <h2>Código: 0192365</h2>
              <h3>Modificado en colaboracion por Jhefer Dair Solano Carrascal</h3>
              <p>Examen Final Arquitectura de Computadores</p>
          </body>
          </html>
          EOF
